#!/bin/bash
#Menu
echo -e ""
echo "--------------------------- Configuration Setup Server -------------------------"
echo "                            Debian Premium Script                               "
echo "                                 -BY KEMADDD-                                   "
echo "--------------------------------------------------------------------------------"
echo -e ""
echo -e "➢ perpanjang: perpanjang masa aktif akun ssh"
echo -e "➢ menu      : menampilkan daftar perintah"
echo -e "➢ usernew   : membuat akun SSH & OpenVPN"
echo -e "➢ trial     : membuat akun trial"
echo -e "➢ hapus     : menghapus akun SSH & OpenVPN"
echo -e "➢ cek       : cek user login"
echo -e "➢ member    : daftar member SSH & OpenVPN"
echo -e "➢ delete    : Delete user expired"
echo -e "➢ restart   : restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "➢ reboot    : reboot VPS"
echo -e "➢ speedtest : speedtest VPS"
echo -e "➢ user limit: membatasi jumlah login ( max 2 )"
echo -e "➢ portstat  : cek status port"
echo -e "➢ info      : menampilkan informasi sistem"
echo -e "➢ contact   : menampilkan kontak penulis script"
echo -e "➢ about     : info script auto install"
echo -e "➢ exit      : keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e "By Kemaddd"
echo -e ""
