#!/bin/bash
#Menu
echo -e ""
echo -e "\e[31;5m+ -- --=[  Script By Kemadddd  ]=-- -- +"

echo -e ""
echo -e ""
echo -e "\e[32;5m               Menu"
echo -e "==================================="
echo -e ""
echo -e "\e[92mPerintah      \e[92mKeterangan"
echo -e "------------         ---------------"
echo -e ""
echo -e "➢ perpanjang:       perpanjang masa aktif akun ssh"
echo -e "➢ menu      :       menampilkan daftar perintah"
echo -e "➢ usernew   :       membuat akun SSH & OpenVPN"
echo -e "➢ trial     :       membuat akun trial"
echo -e "➢ hapus     :       menghapus akun SSH & OpenVPN"
echo -e "➢ cek       :       cek user login"
echo -e "➢ member    :       daftar member SSH & OpenVPN"
echo -e "➢ delete    :       Delete user expired"
echo -e "➢ restart   :       Restart SSH, OpenVPN, Squid, Dropbear"
echo -e "➢ reboot    :       reboot VPS"
echo -e "➢ speedtest :       speedtest VPS"
echo -e "➢ portstat  :       cek status port"
echo -e "➢ info      :       menampilkan informasi sistem"
echo -e "➢ contact   :       menampilkan kontak penulis script"
echo -e "➢ about     :       info script auto install"
echo -e "➢ exit      :       keluar"
echo -e ""
echo "------------------- Menu User Limit --------------------------"
echo -e "➢ limit 1     : membatasi jumlah user MAX 1 login"
echo -e "➢ limit 2     : membatasi jumlah user MAX 2 login"
echo -e "➢ limit stop  : menonaktifkan fitur userlimit"
echo -e "➢ limit cek   : cek log user yang berhasil di kill"
echo -e "➢ limit reset : reset log user yang berhasil di kill"
echo -e ""
echo "------------------- Menu ShadowsocksR -------------------------"
echo -e "➢ ssr         : menampilkan menu ssr"
echo "---------------------------------------------------------------"


echo -e "By Kemaddd"
echo -e ""
