#!/bin/bash
#Menu
echo -e ""
echo -e "\e[31;5m+ -- --=[  Script By Kemadddd  ]=-- -- +"

echo -e ""
echo -e ""
echo -e "\e[96m               Menu"
echo -e "==================================="
echo -e ""
echo -e "  \e[92mPerintah            \e[92mKeterangan"
echo -e "------------          ---------------"
echo -e "➢ \e[37mperpanjang:       \e[37mperpanjang masa aktif akun ssh"
echo -e "➢ \e[37mmenu      :       \e[37mmenampilkan daftar perintah"
echo -e "➢ usernew   :       membuat akun SSH & OpenVPN"
echo -e "➢ trial     :       \e[37mmembuat akun trial"
echo -e "➢ hapus     :       \e[37mmenghapus akun SSH & OpenVPN"
echo -e "➢ cek       :       \e[37mcek user login"
echo -e "➢ member    :       \e[37mdaftar member SSH & OpenVPN"
echo -e "➢ delete    :       Delete user expired"
echo -e "➢ restart   :       Restart SSH, OpenVPN, Squid, Dropbear"
echo -e "➢ reboot    :       reboot VPS"
echo -e "➢ speedtest :       speedtest VPS"
echo -e "➢ portstat  :       \e[37mcek status port"
echo -e "➢ info      :       \e[37mmenampilkan informasi sistem"
echo -e "➢ contact   :       \e[37mmenampilkan kontak penulis script"
echo -e "➢ about     :       info script auto install"
echo -e "➢ exit      :       keluar"
echo -e ""
echo "------------------- Menu User Limit --------------------------"
echo -e ""
echo -e "➢ limit 1     :     \e[37mmembatasi jumlah user MAX 1 login"
echo -e "➢ limit 2     :     \e[37mmembatasi jumlah user MAX 2 login"
echo -e "➢ limit stop  :     \e[37mmenonaktifkan fitur userlimit"
echo -e "➢ limit cek   :     cek log user yang berhasil di kill"
echo -e "➢ limit reset :     reset log user yang berhasil di kill"
echo -e ""
echo "------------------- Menu ShadowsocksR -------------------------"
echo -e ""
echo -e "➢ ssr         :     menampilkan menu ssr"
echo -e ""
echo "---------------------------------------------------------------"


echo -e "By Kemaddd"
echo -e ""
